### ISSUE TITLE
Access Code?

### ISSUE THREAD

**Issue by volt72** [samnyan/aqua-viewer#5]
This is probably really simple but I cannot for the life of me figure out where to get this code, I tried using my card id as the code and the ip of the aqua server in the ApiServer field. They didn't seem to work as I get an error when I try to connect and the server spits out a bunch of garbage.

**Comment by samnyan** [comment]
Access Code is a 20 digit number printed on the back of a card.
You can check the access code by clicking the start button, usually their is a Access Code button next to Guest play button.

And the felica id to Access Code conversion use in aqua is just hex to dec, so you can calculate from the `felica.txt` and padding with 0 in front of it.

Also, you can check it from the `luid` store in the `sega_card` table.

**Comment by volt72** [comment]
Thank you, works perfectly. <3
